### ISSUE TITLE
Syntax highlight

### ISSUE THREAD

**Issue by iwfmp** [ismamz/postcss-utilities#14]
I realise this is not directly relevant to the plugin,
but tried to look for ways to add the '@util' to css/scss syntax highlighting in Atom editor
but couldn't find a reference for it.

Anyone has any advice?

**Comment by ismamz** [comment]
I'm not an Atom's user, but with the package [Sass & SCSS Syntax Highlighting for Atom](https://atom.io/packages/Sass-Syntax-Highlight) you can use scss syntax and works well with `@util` rules.

<img width="365" alt="postcss-syntax" src="https://cloud.githubusercontent.com/assets/3452011/25340969/bb62cf00-28dd-11e7-8bf9-02c15406bee2.png">

You should open a issue in [atom-language-postcss](https://github.com/azat-io/atom-language-postcss) repo, to add this syntax to use in other cases.
