### ISSUE TITLE
"centerMethod" option doesn't work as intended

### ISSUE THREAD

**Issue by xeho91** [ismamz/postcss-utilities#19]
Hi!

I am using this plugin with **webpack** and **postcss-loader** with [postcss-load-config](https://github.com/michael-ciniawsky/postcss-load-config) to load config from package.json.

In **package.json** I've got it configured like this:
```
...
    "postcss": {
        "plugins": {
            "postcss-import": {},
            "postcss-url": {},
            "postcss-utilities": {
                "centerMethod": "flexbox",
                "textHideMethod": "font"
            },
            "postcss-cssnext": {},
            "postcss-browser-reporter": {},
            "postcss-reporter": {}
        }
    },
...
```

And it seems to ignore passed option **"centerMethod"**  - to use **flexbox** centering instead.
It keeps using the default one **transform**.

**However!** Passing option "textHideMethod": "font", works without problems.

I believe there's a typo somewhere, which doesn't switch to flexbox as intended?

**Depedencies:**
"postcss-utilities": "^0.7.0",
"webpack": "^3.8.1",
"postcss-loader": "^2.0.8",

**Comment by xeho91** [comment]
**Edit** I just noticed that you fixed this in latest commit and you didn't publish the fix yet to npm.

**Comment by ismamz** [comment]
Hi! @xeho91 I'll publish the new version very soon!
