### ISSUE TITLE
Add visibility:hidden to clearfix

### ISSUE THREAD

**Issue by PLSFIX** [ismamz/postcss-utilities#20]
Webkit only bug.
[Chromium bugtracker](https://bugs.chromium.org/p/chromium/issues/detail?id=411274)

**Comment by ismamz** [comment]
Hi @PLSFIX Which of the two methods is giving problem?

**Comment by PLSFIX** [comment]
[First one](https://ismamz.github.io/postcss-utilities/docs#clear-fix)
I didn't use ie8 one, but faced the bug described in chrome tracker and had to add visibility rule after hours of digging.

**Comment by ismamz** [comment]
Added for the next version! Sorry for delay
