### ISSUE TITLE
Bug with centerMethod option

### ISSUE THREAD

**Issue by totraev** [ismamz/postcss-utilities#21]
Hi! I found a bug with **centerMethod** option. Problem with number of argument in **center** function. This problem was solved in last pull request, but last version in npm is still 7.0. Can you provide new release?

**Comment by ismamz** [comment]
Hi @totraev! I have a series of changes pending to release in the next version. I'll do it very soon.
Thanks for notice me and stay tuned! 😉

**Comment by ismamz** [comment]
New release!
