### ISSUE TITLE
fixed sticky footer

### ISSUE THREAD

**Issue by olegatro** [ismamz/postcss-utilities#7]
Hi, I wanted ask, why you choose implementation with wrapper ?
I think this realization more clean - http://mystrd.at/modern-clean-css-sticky-footer/
```html
html {
    position: relative;
    min-height: 100%;
}
body {
    margin: 0 0 100px; /* bottom = footer height */
}
footer {
    position: absolute;
    left: 0;
    bottom: 0;
    height: 100px;
    width: 100%;
}
```

**Comment by ismamz** [comment]
Hi!, I've looking for sticky footer implementations and I agree with you that there are better ways to do it.
But, I think that it would be good keep at least two options.
In this [article (Sticky Footer, Five Ways)](https://css-tricks.com/couple-takes-sticky-footer/) we have good examples.

We could use the [flexbox method](http://codepen.io/chriscoyier/pen/RRbKrL) as a "fluid" method and the method that you suggested with the option of use wrapper or apply styles directly on body.

Are you agree with this?

**Comment by olegatro** [comment]
Yes, sounds good.
Anyway nice project. 

I long time to use stylus - and feeling the end of monolithic preprocessors.
So choose the postcss plugins for my boilerplate.

**Comment by ismamz** [comment]
Perfect! I'll update the sticky footer utility shortly.
Feel free to make any contribution or comment about how improve this plugin :wink:

Thanks for support and I glad you find it useful.

**Comment by ismamz** [comment]
Here is the new documentation for [Sticky Footer](https://ismamz.github.io/postcss-utilities/docs#sticky-footer). I keep only the fixed height method. Other methods are complex to use as mixins.

**Comment by marcustisater** [comment]
+1
