### ISSUE TITLE
@util position if all 0 doesn't work

### ISSUE THREAD

**Issue by kbytin** [ismamz/postcss-utilities#8]
I get error in this situation 
@util position(absolute, 0 0 0 0)

and everything is fine in this 
@util position(absolute, 0px 0 0 0)

**Comment by ismamz** [comment]
There was a bug. I fix it in [v0.6.1](https://github.com/ismamz/postcss-utilities/commit/aa917c5552389ea10f70bdd593d5244c3c1ad9a0). The new version is published.

Thanks for reporting. If you find another bug, let me know!
